version: '3'

tasks:
  format:
    cmds:
    - deno fmt README.md
    - gofmt -w .
  lint: golangci-lint run --fix --timeout "10m"
  test: go test -bench=. -benchmem
  default:
    cmds:
    - task: format
    - task: lint
    - task: test
